-- MySQL Script generated by MySQL Workbench
-- Fri Aug 15 21:30:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema chela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chela` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `chela` ;

-- -----------------------------------------------------
-- Table `chela`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `nombre_categoria` (`nombre_categoria` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(25) NOT NULL,
  `fecha_registro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_clientes`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`proveedores` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `contacto` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedor`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`productos` (
  `id_productos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `talle` VARCHAR(25) NOT NULL,
  `stock` INT NOT NULL,
  `categoria` INT NULL DEFAULT NULL,
  `id_proveedor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_productos`),
  INDEX `fk_productos_proveedores` (`id_proveedor` ASC) VISIBLE,
  INDEX `fk_productos_categorias` (`categoria` ASC) VISIBLE,
  CONSTRAINT `fk_productos_categorias`
    FOREIGN KEY (`categoria`)
    REFERENCES `chela`.`categorias` (`id_categoria`),
  CONSTRAINT `fk_productos_proveedores`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `chela`.`proveedores` (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `calificacion` TINYINT NULL DEFAULT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `fecha_comentario` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_comentario`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `comentarios_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `chela`.`clientes` (`id_clientes`),
  CONSTRAINT `comentarios_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `chela`.`productos` (`id_productos`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`cupones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`cupones` (
  `id_cupon` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `tipo_descuento` ENUM('porcentaje', 'monto fijo') NOT NULL,
  `fecha_vencimiento` DATE NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_cupon`),
  UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(25) NOT NULL,
  `rol` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`medios_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`medios_pago` (
  `id_medio_pago` INT NOT NULL AUTO_INCREMENT,
  `nombre_medio` VARCHAR(50) NOT NULL,
  `activo` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_medio_pago`),
  UNIQUE INDEX `nombre_medio` (`nombre_medio` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_pedido` DATE NOT NULL,
  `estado_pedido` VARCHAR(45) NOT NULL,
  `total_pedido` DECIMAL(10,2) NOT NULL,
  `metodo_pago` INT NULL DEFAULT NULL,
  `id_cupon` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`, `id_cliente`, `id_usuario`),
  INDEX `fk_id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_pedidos_medios_pago` (`metodo_pago` ASC) VISIBLE,
  INDEX `fk_pedidos_cupones` (`id_cupon` ASC) VISIBLE,
  CONSTRAINT `fk_id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `chela`.`clientes` (`id_clientes`),
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `chela`.`usuarios` (`id_usuario`),
  CONSTRAINT `fk_pedidos_cupones`
    FOREIGN KEY (`id_cupon`)
    REFERENCES `chela`.`cupones` (`id_cupon`),
  CONSTRAINT `fk_pedidos_medios_pago`
    FOREIGN KEY (`metodo_pago`)
    REFERENCES `chela`.`medios_pago` (`id_medio_pago`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`detalles_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`detalles_pedido` (
  `id_detalles_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_venta` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_detalles_pedido`, `id_pedido`, `id_producto`),
  INDEX `fk_id_pedido_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `fk_id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_id_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `chela`.`pedidos` (`id_pedido`),
  CONSTRAINT `fk_id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `chela`.`productos` (`id_productos`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`devoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`devoluciones` (
  `id_devolucion` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `motivo` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_devolucion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_devolucion`),
  INDEX `id_pedido` (`id_pedido` ASC) VISIBLE,
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `devoluciones_ibfk_1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `chela`.`pedidos` (`id_pedido`),
  CONSTRAINT `devoluciones_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `chela`.`productos` (`id_productos`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`eventos_marketing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`eventos_marketing` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `nombre_evento` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `presupuesto` DECIMAL(10,2) NULL DEFAULT NULL,
  `tipo_evento` ENUM('campaña publicitaria', 'liquidación', 'evento especial') NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`movimientos_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`movimientos_stock` (
  `id_movimiento` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `tipo_movimiento` ENUM('entrada', 'salida') NOT NULL,
  `cantidad` INT NOT NULL,
  `fecha_movimiento` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `motivo` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_movimiento`),
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `movimientos_stock_ibfk_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `chela`.`productos` (`id_productos`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`promociones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`promociones` (
  `id_promocion` INT NOT NULL AUTO_INCREMENT,
  `nombre_promocion` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `tipo_descuento` VARCHAR(45) NOT NULL,
  `valor_descuento` DECIMAL(10,2) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `aplicable_a` VARCHAR(45) NOT NULL,
  `id_evento` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_promocion`),
  INDEX `fk_promociones_eventos_marketing` (`id_evento` ASC) VISIBLE,
  CONSTRAINT `fk_promociones_eventos_marketing`
    FOREIGN KEY (`id_evento`)
    REFERENCES `chela`.`eventos_marketing` (`id_evento`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chela`.`producto_promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chela`.`producto_promocion` (
  `id_producto_promocion` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_promocion` INT NOT NULL,
  `fecha_aplicacion_inicio` DATE NOT NULL,
  `fecha_aplicacion_fin` DATE NOT NULL,
  PRIMARY KEY (`id_producto_promocion`, `id_producto`, `id_promocion`),
  INDEX `fk_id_prod_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_id_promo_idx` (`id_promocion` ASC) VISIBLE,
  CONSTRAINT `fk_id_prod`
    FOREIGN KEY (`id_producto`)
    REFERENCES `chela`.`productos` (`id_productos`),
  CONSTRAINT `fk_id_promo`
    FOREIGN KEY (`id_promocion`)
    REFERENCES `chela`.`promociones` (`id_promocion`))
ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
